### ISSUE TITLE
missing shader "ConstantShader (TextureTransform)"

### ISSUE THREAD

**Issue by mhusinsky** [bj-rn/VL.Addons#1]
hi,

the "QuadRenderer (TextureTransform)" node contains the shader "ConstantShader (TextureTransform)", which is missing in the nuget (v.0.0.5).

![grafik](https://user-images.githubusercontent.com/3253299/224722663-92175f52-8a1c-477f-9ab0-7b6d98029276.png)

the nice spritesheet player is therefore broken.

**Comment by bj-rn** [comment]
Hello,

all Shaders were missing in the package, forgot to add them to the nuspec file ...
Fixed with the latest version (0.0.6).
