### ISSUE TITLE
Echo output is always 16bit per channel

### ISSUE THREAD

**Issue by YanYas** [bj-rn/VL.Addons#16]
The echo node converts the input to 16 bit, which is understandable to create the information bandwidth for the effect to work well, but maybe it should convert back to the original input, or have an override option.

**Comment by bj-rn** [comment]
Hi, _Echo_ only really achieves the desired result when using 16 (or 32) bit and I really don't want to put a _ChangeFormat_ node inside. So I'd suggest to to "just" use ChangeFormat afterwards or check out _ComputeFeedback_ which can produce similar effects.
